name: BlockfrostSwiftSDK
targets:
  OpenAPIClient:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: [BlockfrostSwiftSDK]
    info:
      path: ./Info.plist
      version: 0.1.27
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
    - carthage: Alamofire
#    - carthage: AwaitKit
#    - carthage: SwiftCoroutine
