//
// AccountRegistrationContent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class AccountRegistrationContent: Codable, Hashable {
    public enum Action: String, Codable, CaseIterable {
        case registered
        case deregistered
    }

    /** Hash of the transaction containing the (de)registration certificate */
    public var txHash: String
    /** Action in the certificate */
    public var action: Action

    public init(txHash: String, action: Action) {
        self.txHash = txHash
        self.action = action
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case txHash = "tx_hash"
        case action
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(txHash, forKey: .txHash)
        try container.encode(action, forKey: .action)
    }

    public static func == (lhs: AccountRegistrationContent, rhs: AccountRegistrationContent) -> Bool {
        lhs.txHash == rhs.txHash &&
            lhs.action == rhs.action
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txHash.hashValue)
        hasher.combine(action.hashValue)
    }
}
