//
// AccountMirContent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class AccountMirContent: Codable, Hashable {
    /** Hash of the transaction containing the MIR */
    public var txHash: String
    /** MIR amount in Lovelaces */
    public var amount: String

    public init(txHash: String, amount: String) {
        self.txHash = txHash
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case txHash = "tx_hash"
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(txHash, forKey: .txHash)
        try container.encode(amount, forKey: .amount)
    }

    public static func == (lhs: AccountMirContent, rhs: AccountMirContent) -> Bool {
        lhs.txHash == rhs.txHash &&
            lhs.amount == rhs.amount
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txHash.hashValue)
        hasher.combine(amount.hashValue)
    }
}
