//
// InlineResponse200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiRoot: Codable, Hashable {

    public var url: String
    public var version: String

    public init(url: String, version: String) {
        self.url = url
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(version, forKey: .version)
    }
}

