//
// AssetAddress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class AssetAddress: Codable, Hashable {
    /** Address containing the specific asset */
    public var address: String
    /** Asset quantity on the specific address */
    public var quantity: String

    public init(address: String, quantity: String) {
        self.address = address
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(quantity, forKey: .quantity)
    }

    public static func == (lhs: AssetAddress, rhs: AssetAddress) -> Bool {
        lhs.address == rhs.address &&
            lhs.quantity == rhs.quantity
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(address.hashValue)
        hasher.combine(quantity.hashValue)
    }
}
