//
// Asset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class AssetRecord: Codable, Hashable {
    /** Hex-encoded asset full name */
    public var asset: String
    /** Current asset quantity */
    public var quantity: String

    public init(asset: String, quantity: String) {
        self.asset = asset
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case asset
        case quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(asset, forKey: .asset)
        try container.encode(quantity, forKey: .quantity)
    }

    public static func == (lhs: AssetRecord, rhs: AssetRecord) -> Bool {
        lhs.asset == rhs.asset &&
            lhs.quantity == rhs.quantity
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(asset.hashValue)
        hasher.combine(quantity.hashValue)
    }
}
