//
// InlineResponse2001.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Health: Codable, Hashable {

    public var isHealthy: Bool

    public init(isHealthy: Bool) {
        self.isHealthy = isHealthy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isHealthy = "is_healthy"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isHealthy, forKey: .isHealthy)
    }
}

