//
// InlineResponse2003.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IPFSObject: Codable, Hashable {

    /** Name of the file */
    public var name: String
    /** IPFS hash of the file */
    public var ipfsHash: String
    /** IPFS node size in Bytes */
    public var size: String

    public init(name: String, ipfsHash: String, size: String) {
        self.name = name
        self.ipfsHash = ipfsHash
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case ipfsHash = "ipfs_hash"
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(ipfsHash, forKey: .ipfsHash)
        try container.encode(size, forKey: .size)
    }
}

