//
// Metric.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class Metric: Codable, Hashable {
    /** Starting time of the call count interval (ends midnight UTC) in UNIX time */
    public var time: Int
    /** Sum of all calls for a particular day */
    public var calls: Int

    public init(time: Int, calls: Int) {
        self.time = time
        self.calls = calls
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case calls
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(time, forKey: .time)
        try container.encode(calls, forKey: .calls)
    }

    public static func == (lhs: Metric, rhs: Metric) -> Bool {
        lhs.time == rhs.time &&
            lhs.calls == rhs.calls
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(time.hashValue)
        hasher.combine(calls.hashValue)
    }
}
