//
// NutlinkAddressTicker.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class NutlinkAddressTicker: Codable, Hashable {
    /** Hash of the transaction */
    public var txHash: String
    /** Block height of the record */
    public var blockHeight: Int
    /** Transaction index within the block */
    public var txIndex: Int
    /** Content of the ticker */
    public var payload: AnyCodable

    public init(txHash: String, blockHeight: Int, txIndex: Int, payload: AnyCodable) {
        self.txHash = txHash
        self.blockHeight = blockHeight
        self.txIndex = txIndex
        self.payload = payload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case txHash = "tx_hash"
        case blockHeight = "block_height"
        case txIndex = "tx_index"
        case payload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(txHash, forKey: .txHash)
        try container.encode(blockHeight, forKey: .blockHeight)
        try container.encode(txIndex, forKey: .txIndex)
        try container.encode(payload, forKey: .payload)
    }

    public static func == (lhs: NutlinkAddressTicker, rhs: NutlinkAddressTicker) -> Bool {
        lhs.txHash == rhs.txHash &&
            lhs.blockHeight == rhs.blockHeight &&
            lhs.txIndex == rhs.txIndex &&
            CodableHelper.eqAny(lhs.payload, rhs.payload)
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txHash.hashValue)
        hasher.combine(blockHeight.hashValue)
        hasher.combine(txIndex.hashValue)
        hasher.combine(payload.hashValue)
    }
}
