//
// InlineResponse2004.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PinResponse: Codable, Hashable {

    public enum State: String, Codable, CaseIterable {
        case queued = "queued"
        case pinned = "pinned"
        case unpinned = "unpinned"
        case failed = "failed"
        case gc = "gc"
    }
    /** IPFS hash of the pinned object */
    public var ipfsHash: String
    /** State of the pin action */
    public var state: State

    public init(ipfsHash: String, state: State) {
        self.ipfsHash = ipfsHash
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ipfsHash = "ipfs_hash"
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ipfsHash, forKey: .ipfsHash)
        try container.encode(state, forKey: .state)
    }
}

