//
// PoolUpdat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class PoolUpdate: Codable, Hashable {
    public enum Action: String, Codable, CaseIterable {
        case registered
        case deregistered
    }

    /** Transaction ID */
    public var txHash: String
    /** Certificate within the transaction */
    public var certIndex: Int
    /** Action in the certificate */
    public var action: Action

    public init(txHash: String, certIndex: Int, action: Action) {
        self.txHash = txHash
        self.certIndex = certIndex
        self.action = action
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case txHash = "tx_hash"
        case certIndex = "cert_index"
        case action
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(txHash, forKey: .txHash)
        try container.encode(certIndex, forKey: .certIndex)
        try container.encode(action, forKey: .action)
    }

    public static func == (lhs: PoolUpdate, rhs: PoolUpdate) -> Bool {
        lhs.txHash == rhs.txHash &&
            lhs.certIndex == rhs.certIndex &&
            lhs.action == rhs.action
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txHash.hashValue)
        hasher.combine(certIndex.hashValue)
        hasher.combine(action.hashValue)
    }
}
