//
// Status.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Status: Codable, Hashable {

    public var statusCode: Int? = nil
    public var error: String? = nil
    public var message: String? = nil

    public init(statusCode: Int?, error: String?, message: String?) {
        self.statusCode = statusCode
        self.error = error
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case statusCode = "status_code"
        case error
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(statusCode, forKey: .statusCode)
        try container.encode(error, forKey: .error)
        try container.encode(message, forKey: .message)
    }
}

