//
// TxContentMetadataCbor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class TxContentMetadataCbor: Codable, Hashable {
    /** Metadata label */
    public var label: String
    /** Content of the CBOR metadata */
    public var cborMetadata: String?

    public init(label: String, cborMetadata: String?) {
        self.label = label
        self.cborMetadata = cborMetadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case cborMetadata = "cbor_metadata"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(label, forKey: .label)
        try container.encode(cborMetadata, forKey: .cborMetadata)
    }

    public static func == (lhs: TxContentMetadataCbor, rhs: TxContentMetadataCbor) -> Bool {
        lhs.label == rhs.label &&
            lhs.cborMetadata == rhs.cborMetadata
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(label.hashValue)
        hasher.combine(cborMetadata.hashValue)
    }
}
