//
// TxContentWithdrawal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class TxContentWithdrawal: Codable, Hashable {
    /** Bech32 withdrawal address */
    public var address: String
    /** Withdrawal amount in Lovelaces */
    public var amount: String

    public init(address: String, amount: String) {
        self.address = address
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(amount, forKey: .amount)
    }

    public static func == (lhs: TxContentWithdrawal, rhs: TxContentWithdrawal) -> Bool {
        lhs.address == rhs.address &&
            lhs.amount == rhs.amount
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(address.hashValue)
        hasher.combine(amount.hashValue)
    }
}
