//
// TxContentUtxo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class TxContentUtxo: Codable, Hashable {
    /** Transaction hash */
    public var hash: String
    public var inputs: [TxContentUtxoInputs]
    public var outputs: [TxContentUtxoOutputs]

    public init(hash: String, inputs: [TxContentUtxoInputs], outputs: [TxContentUtxoOutputs]) {
        self.hash = hash
        self.inputs = inputs
        self.outputs = outputs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hash
        case inputs
        case outputs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hash, forKey: .hash)
        try container.encode(inputs, forKey: .inputs)
        try container.encode(outputs, forKey: .outputs)
    }

    public static func == (lhs: TxContentUtxo, rhs: TxContentUtxo) -> Bool {
        lhs.hash == rhs.hash &&
            lhs.inputs == rhs.inputs &&
            lhs.outputs == rhs.outputs
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(hash.hashValue)
        hasher.combine(inputs.hashValue)
        hasher.combine(outputs.hashValue)
    }
}
