//
// TxMetadataLabelJson.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public final class TxMetadataLabelJson: Codable, Hashable {
    /** Transaction hash that contains the specific metadata */
    public var txHash: String
    /** Content of the JSON metadata */
    public var jsonMetadata: [String:AnyCodable]

    public init(txHash: String, jsonMetadata: [String:AnyCodable]) {
        self.txHash = txHash
        self.jsonMetadata = jsonMetadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case txHash = "tx_hash"
        case jsonMetadata = "json_metadata"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(txHash, forKey: .txHash)
        try container.encode(jsonMetadata, forKey: .jsonMetadata)
    }

    public static func == (lhs: TxMetadataLabelJson, rhs: TxMetadataLabelJson) -> Bool {
        lhs.txHash == rhs.txHash &&
            CodableHelper.codableHashEqual(lhs.jsonMetadata, rhs.jsonMetadata) &&
            CodableHelper.codableDeepEqual(lhs.jsonMetadata, rhs.jsonMetadata)
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txHash.hashValue)
        hasher.combine(jsonMetadata.hashValue)
    }
}
