name: tests

on:
  push:
    branches: [master, test]
  pull_request:
    branches: [master]

jobs:
  macos_big_sur:
    runs-on: macos-11.0

    strategy:
      matrix:
        xcode:
          - "13"

    name: "macOS Big Sur (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-
      - name: Build and Test
        run: |
          swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
          BF_MAINNET_PROJECT_ID: ${{ secrets.BF_MAINNET_PROJECT_ID }}
          BF_IPFS_PROJECT_ID: ${{ secrets.BF_IPFS_PROJECT_ID }}

#  linux:
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        swift:
#          - "5.4"
#
#    name: "Linux (Swift ${{ matrix.swift }})"
#
#    container:
#      image: swift:${{ matrix.swift }}
#      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Build and Test
#        env:
#          BF_MAINNET_PROJECT_ID: ${{ secrets.BF_MAINNET_PROJECT_ID }}
#          BF_IPFS_PROJECT_ID: ${{ secrets.BF_IPFS_PROJECT_ID }}
#        run: |
#          swift test --enable-test-discovery